export type PartId = 'body'|'glass'|'doors'|'cabin'|'battery'|'drive'|'suspension'|'wheels';
const manual = 'https://www.tesla.com/ownersmanual/modelx/en_us/';
export const parts: {id:PartId;name:string;category:string;tag:string;description:string;principle:string;specs:[string,string][];source:string}[] = [
{id:'body',name:'Body & structure',category:'Exterior',tag:'THE PROTECTIVE SHELL',description:'The body brings the vehicle together: an enclosed passenger space, crumple zones at either end, and a smooth exterior that guides air around the car.',principle:'The structure carries loads around the cabin, while the hood and liftgate give access to separate front and rear storage areas.',specs:[['Role','Structure & protection'],['Location','Vehicle exterior']],source:manual+'GUID-7A32EC01-A17E-42CC-A15B-2E0A39FD07AB.html'},
{id:'glass',name:'Panoramic glass',category:'Exterior',tag:'A WIDER VIEW',description:'The expansive windshield sweeps up above the front seats, opening the cabin to more of the world outside.',principle:'The windshield and side glazing create visibility around the vehicle. The overhead glass sections move with the falcon wing doors.',specs:[['Role','Visibility & enclosure'],['Position','Upper cabin']],source:manual+'GUID-F617DA3E-11C1-4FBA-98A7-A9C3828E3536.html'},
{id:'doors',name:'Doors & falcon wings',category:'Exterior',tag:'ENGINEERING THAT OPENS UP',description:'Two hinges give each rear door its distinctive upward motion. The door folds as it rises, making access possible in tighter spaces.',principle:'Sensors check for obstacles while the powered hinges coordinate the opening path. Available clearance influences how high the door opens.',specs:[['Motion','Dual-hinged'],['Operation','Electrically powered']],source:manual+'GUID-7A32EC01-A17E-42CC-A15B-2E0A39FD07AB.html'},
{id:'cabin',name:'Passenger cabin',category:'Interior',tag:'BUILT AROUND PEOPLE',description:'The passenger space sits above the battery. Seats, restraints, controls and displays form the part of the vehicle you interact with every day.',principle:'A flat electric platform leaves room for multiple seating configurations. The imported model includes modeled seating and trim. Its cabin reflects the older source car; actual seating and controls vary by year and configuration.',specs:[['Shown here','Source-model interior'],['Position','Above battery']],source:manual+'GUID-F617DA3E-11C1-4FBA-98A7-A9C3828E3536.html'},
{id:'battery',name:'High-voltage battery',category:'Energy',tag:'THE ENERGY FOUNDATION',description:'A liquid-cooled lithium-ion battery stores the energy that powers the vehicle. Positioned beneath the cabin, it supplies the electric drive units.',principle:'Electrical energy flows to the motors during acceleration. During regenerative braking, the motors can convert vehicle motion back into energy stored in the battery.',specs:[['Chemistry','Lithium-ion'],['Cooling','Liquid-cooled']],source:manual+'GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html'},
{id:'drive',name:'Electric drive units',category:'Powertrain',tag:'ENERGY INTO MOTION',description:'Electric motors turn stored energy into wheel torque. This dual-motor study places one drive unit at the front and another at the rear.',principle:'An inverter controls each motor, and a fixed-ratio gearbox transfers rotation to the wheels. The motors also help slow the vehicle through regenerative braking.',specs:[['Layout','Front + rear'],['Transmission','Single-speed'],['Configuration','Dual motor']],source:manual+'GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html'},
{id:'suspension',name:'Adaptive suspension',category:'Chassis',tag:'CONNECTED TO THE ROAD',description:'Air springs support the car while adaptive dampers control body movement. The system can adjust ride height and the way the car responds to the road.',principle:'Front double-wishbone and rear multi-link suspension guide each wheel. Air pressure changes support height, while damping balances comfort with control.',specs:[['Springs','Air'],['Damping','Adaptive'],['Height','Adjustable']],source:manual+'GUID-F1B6801A-8946-41AD-8CF9-7A963CDA38E4.html'},
{id:'wheels',name:'Wheels & brakes',category:'Chassis',tag:'WHERE MOTION MEETS GRIP',description:'The tires are the vehicle’s contact with the road. Behind each wheel, a ventilated brake disc and caliper provide friction braking.',principle:'Regenerative braking recovers energy through the motors. Friction brakes provide additional stopping force, with ABS helping control wheel slip.',specs:[['Brakes','Ventilated discs'],['Control','Four-wheel ABS'],['Energy recovery','Regenerative braking']],source:manual+'GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html'},
];

export function describePiece(label:string):string {
 const name=label.split(' · ')[0];
 const explanations:Record<string,string>={
  'Hood':'The hood closes the front luggage compartment. Its outer surface continues the body’s aerodynamic shape, while hinges and a latch allow access to the storage space.',
  'Front bumper':'The front bumper cover forms the nose of the vehicle and surrounds its lower openings. The visible cover is separate from the impact structure behind it.',
  'Rear bumper':'The rear bumper cover finishes the lower rear body. It is the visible outer panel, rather than the impact beam hidden underneath.',
  'Liftgate panel':'The liftgate closes the rear cargo opening. It carries exterior trim and works with hinges, powered supports and a latch to provide access to the trunk.',
  'Front door panel':'This panel forms part of a conventionally hinged front door. The complete door also contains glazing, a latch, seals and interior trim.',
  'Falcon wing door panel':'This panel belongs to the rear door assembly. On the real car, two hinges coordinate its upward folding motion; this explorer separates the geometry rather than simulating the exact hinge path.',
  'Fender / quarter panel':'This exterior panel shapes the body around a wheel opening. Its position helps enclose the wheel well and connects the silhouette to adjacent doors and bumpers.',
  'Glazing':'This is a modeled section of vehicle glazing. Depending on its location, it provides forward, side or rear visibility, or an overhead view. The dark tint here is a rendering material.',
  'Body trim and seals':'Trim finishes panel edges and transitions; seals help close gaps against weather and noise. This mesh is a visual representation, not a separately verified replacement part.',
  'Rear lighting element':'A rear lamp element helps communicate the vehicle’s presence and driving intentions. The asset separates lamp shapes, but does not specify the electrical function of every individual lens.',
  'Front lighting element':'This shape belongs to the front lighting assembly. The complete assembly combines lenses, light sources and reflectors to illuminate the road or signal the vehicle’s presence.',
  'Tesla emblem':'The exterior emblem identifies the vehicle’s maker. It is a decorative badge rather than part of the propulsion or body structure.',
  'Side mirror':'The mirror provides a view alongside and behind the vehicle. The full assembly includes the reflective glass, housing and adjustment mechanism.',
  'Chrome trim':'This metallic trim finishes an exterior edge or accent. Its appearance and placement reflect the older Model X represented by the source artist.',
  'Lower trim and liner':'This modeled piece forms part of the lower body finish or a liner. Such pieces cover exposed areas and help manage spray, debris and airflow.',
  'Tire and tread':'The tire is the contact surface between the vehicle and the road. Its rubber compound, tread and inflation support the load and influence grip, comfort and rolling resistance.',
  'Brake disc':'The brake disc turns with the wheel. Brake pads clamp it to convert motion into heat during friction braking, supplementing the motors’ regenerative braking.',
  'Wheel fastener':'Wheel fasteners clamp the wheel to its hub. This is the source artist’s geometry; it does not supply a verified thread specification or service torque.',
  'Alloy wheel detail':'This mesh is part of the modeled alloy wheel. The wheel supports the tire and transfers loads between it and the hub; spokes connect the hub area to the rim.',
  'Interior trim and seating':'This is a piece of the modeled passenger compartment. The source separates seating and trim into mesh islands without assigning manufacturer part numbers.',
  'Exterior detail':'This is an individual exterior mesh from the source model. Its precise service-part identity is unverified; use its placement and the system overview for context.'
 };
 return explanations[name]||'This is a separate piece of the source model. Its label describes the visible geometry; an exact Tesla service-part identity is not supplied.';
}
